nav_wps:
    # waypoints reference frame
    waypoint_frameid: map

    # waypoint 2D coordinates: x, y, theta
    wp0: [0, 0.4, -1.57]
    wp1: [3.7, -1.2, -1.57]
    wp2: [3.7, -2.0, -1.57]
    wp3: [1.7, -1.7, 1.57]
